config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :posts do
		resources :likes
		resources :comments
	end

	constraints Clearance::Constraints::SignedIn.new do
    root to: "posts#index", as: :signed_in_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
	belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments

	mount_uploader :photo, PhotoUploader

	def time_posted(date_posted)
		current_date = Time.now
		time_elapsed = current_date - date_posted 

		if time_elapsed >	(3600 * 24)
			days = time_elapsed / (3600 * 24)
			return "#{days.floor}d ago"
		elsif time_elapsed > 3600
			hours = time_elapsed / 3600
			return "#{hours.floor}h ago"
		else
			minutes = time_elapsed / 60
			return "#{minutes.floor}m ago"
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

	has_many :posts
	has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])

		@comment = @post.comments.new(comment_params)
		@comment.user_id = current_user.id
		@comment.save!

		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def new
	end

	def create
		@user = current_user.id
		@post = params[:post_id]
		@score = params[:score]

		like_exists = Like.find_by(user_id: @user, post_id: @post)
		unless like_exists
			@like = Like.new({user_id: @user, post_id: @post, score: @score})
			@like.save!
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_login

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
	end

	def create
		@post = Post.create(post_params)
		redirect_to @post
	end

	private

	def post_params
		params.require(:post).permit(:title, :text, :photo).merge(user_id: current_user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
	<% if signed_in? %>
		Signed in as: <%= current_user.email %>
		<%= button_to 'Sign out', sign_out_path, method: :delete %>
	<% else %>
		<%= link_to 'Sign in', sign_in_path %>
	<% end %>

	<div id="flash">
		<% flash.each do |key, value| %>
			<div class="flash <%= key %>"><%= value %></div>
		<% end %>
	</div>

	<%= link_to 'New Post', new_post_path %>

	<h1>Posts:</h1>
		<% @posts.reverse.each do |post| %>
			<p>
				<strong> <%= User.find(post.user_id).email %>: <%= post.title %></strong> 
				<%= post.time_posted(post.created_at) %> <br>
				<%= post.text %><br>
				<% unless post.photo.file.nil? %>
					<%= image_tag post.photo %> <!-- .thumb? -->
				<% end %></br>
				<%= link_to 'Show', post_path(post) %>
				Average rating: 
				<% if Like.where(post_id: post.id).size > 0 %>
					<%= Like.where(post_id: post.id).sum(:score) / Like.where(post_id: post.id).size %> 
				<% else %>
						n/a
				<% end %>
			Your rating: 
			<% for i in 1..5 %>
				<%= link_to i.to_s, post_likes_path(post, score: i), method: :post %> 
			<% end %>
			</p>
		<% end %>
	</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>

	<body>
		<%= form_for :post, url: posts_path do |f| %>
			<p>
				<%= f.label :title %></br>
				<%= f.text_field :title %> 
			</p>
			<p>
				<%= f.label :text %> </br>
				<%= f.text_area :text %> 
			</p>
			<p>
				<%= f.label :photo %></br>
				<%= f.file_field :photo %>
			</p>
			<p>
				<%= f.submit %>
			</p>
		<% end %>
	</body>
</html>

app/views/posts/show.html.erb
<html>
	<body>
		<%= link_to 'All Posts', posts_path %>
		<p>
			<strong><%= @post.title %></strong><br>
			<%= @post.text %><br>
			<% unless @post.photo.file.nil? %>
				<%= image_tag @post.photo %> <!-- .thumb? -->
			<% end %></br>


			Average Rating: 
				<% if Like.where(post_id: @post.id).size > 0 %>
					<%= Like.where(post_id: @post.id).sum(:score) / Like.where(post_id: @post.id).size %> 
				<% else %>
						n/a
				<% end %>
			Your rating: 
			<% for i in 1..5 %>
				<%= link_to i.to_s, post_likes_path(@post, score: i), method: :post %> 
			<% end %>
		</p>

		<h2>Comments</h2>
		<% @post.comments.reverse.each do |comment| %>
			<p> 
				<strong><%= User.find(comment.user_id).email %> wrote: </strong></br>
				<%= comment.body %>
			</p>
		<% end %>	

		<h3>Add a comment:</h3>
		<%= form_for([@post, @post.comments.build]) do |f| %>
			<p>
				<%= f.text_area :body %>
			</p>
			<p>
				<%= f.submit %>
			</p>
		<% end %>
	</body>
</html>